import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { isProductionEnv } from "@/lib/utils";
import PWAInstallationPrompt from "./_components/PWAInstallationPrompt";
import ServiceWorkerUpdatePrompt from "./_components/ServiceWorkerUpdatePrompt";
import QueryClientProvider from "./_providers/QueryClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <QueryClientProvider>{children}</QueryClientProvider>

        {isProductionEnv && <PWAInstallationPrompt />}
        {isProductionEnv && <ServiceWorkerUpdatePrompt />}
      </body>
    </html>
  );
}
