import type { Metadata } from "next";
import "./globals.css";
import { isProductionEnv } from "@/lib/utils";
import PWAInstallationPrompt from "./_components/PWAInstallationPrompt";
import ServiceWorkerUpdatePrompt from "./_components/ServiceWorkerUpdatePrompt";
import { Providers } from "./_providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>

        {isProductionEnv && <PWAInstallationPrompt />}
        {isProductionEnv && <ServiceWorkerUpdatePrompt />}
      </body>
    </html>
  );
}
